name: Running Bot

on:
  workflow_dispatch:
  repository_dispatch:
    types: [cron_job]
concurrency:
  group: ${{ github.workflow }}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get dotenv
        run: echo ${{ secrets.DOTENV }} | base64 --decode > .env

      - name: Download Binary
        uses: robinraju/release-downloader@v1.12
        with:
          latest: true
          fileName: sobatlpg

      - name: Cache browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/rod
          key: ${{ runner.os }}-browser-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-browser-
  
      - name: Run
        run: |
          chmod +x ./sobatlpg
          ./sobatlpg --proxy

      - name: Push Result
        if: ${{ always() }}
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"
          git add database/*
          git commit -m "update data"
          git push origin main

      - name: Call dispatch
        if: ${{always()}}
        uses: peter-evans/repository-dispatch@v3.0.0
        with:
          event-type: cron_job
